export interface Product {
  id: number;
  slug: string;
  name: string;
  category: string;
  categoryLabel: string;
  price: number;
  unit: string;
  originalPrice: number;
  images: string[];
  badge: string;
  badgeColor: string;
  farm: string;
  farmLocation: string;
  rating: number;
  reviewCount: number;
  sold: number;
  description: string;
  highlights: string[];
  nutrition: { label: string; value: string }[];
  weight: string;
  expiry: string;
  origin: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "rau-cai-xanh-huu-co",
    name: "Rau cải xanh hữu cơ",
    category: "rau",
    categoryLabel: "Rau xanh",
    price: 35000,
    unit: "500g",
    originalPrice: 45000,
    images: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Mới nhất",
    badgeColor: "bg-green-500",
    farm: "Nông trại Đà Lạt",
    farmLocation: "Đà Lạt, Lâm Đồng",
    rating: 4.9,
    reviewCount: 328,
    sold: 1240,
    description: "Rau cải xanh hữu cơ được trồng tại vùng đất cao nguyên Đà Lạt với khí hậu mát mẻ quanh năm. Không phân bón hóa học, không thuốc trừ sâu — chỉ phân hữu cơ vi sinh và nước suối tự nhiên. Thu hoạch buổi sáng, giao trong ngày.",
    highlights: [
      "Chứng nhận USDA Organic & VietGAP",
      "Thu hoạch trong vòng 24h trước khi giao",
      "Trồng bằng phân hữu cơ vi sinh",
      "Không chất bảo quản, không sáp coating",
    ],
    nutrition: [
      { label: "Calories", value: "23 kcal / 100g" },
      { label: "Protein", value: "2.1g" },
      { label: "Carbohydrates", value: "3.6g" },
      { label: "Chất xơ", value: "2.2g" },
      { label: "Vitamin C", value: "89mg (99% DV)" },
      { label: "Canxi", value: "74mg" },
    ],
    weight: "500g ± 50g",
    expiry: "5–7 ngày trong ngăn mát tủ lạnh",
    origin: "Đà Lạt, Lâm Đồng",
  },
  {
    id: 2,
    slug: "ca-rot-baby-huu-co",
    name: "Cà rốt baby hữu cơ",
    category: "cu-qua",
    categoryLabel: "Củ & Quả",
    price: 42000,
    unit: "500g",
    originalPrice: 58000,
    images: [
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1447175008436-054170c2e979?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Bán chạy",
    badgeColor: "bg-amber-500",
    farm: "Nông trại Mộc Châu",
    farmLocation: "Mộc Châu, Sơn La",
    rating: 4.8,
    reviewCount: 512,
    sold: 2180,
    description: "Cà rốt baby hữu cơ từ cao nguyên Mộc Châu — ngọt tự nhiên, giòn và đầy beta-carotene. Được trồng theo phương pháp canh tác hữu cơ truyền thống, không phân bón hóa học.",
    highlights: [
      "Ngọt hơn 30% so với cà rốt thường",
      "Hàm lượng beta-carotene cao",
      "Thu hoạch thủ công từng củ",
      "Phù hợp cho trẻ em và người ăn kiêng",
    ],
    nutrition: [
      { label: "Calories", value: "41 kcal / 100g" },
      { label: "Beta-carotene", value: "8285μg" },
      { label: "Vitamin A", value: "835μg (93% DV)" },
      { label: "Carbohydrates", value: "9.6g" },
      { label: "Chất xơ", value: "2.8g" },
      { label: "Kali", value: "320mg" },
    ],
    weight: "500g ± 30g",
    expiry: "10–14 ngày trong ngăn mát tủ lạnh",
    origin: "Mộc Châu, Sơn La",
  },
  {
    id: 3,
    slug: "bo-hass-huu-co",
    name: "Bơ Hass hữu cơ",
    category: "trai-cay",
    categoryLabel: "Trái cây",
    price: 85000,
    unit: "2 quả",
    originalPrice: 110000,
    images: [
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587915592156-b61f7e2e5a6c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Hot",
    badgeColor: "bg-rose-500",
    farm: "Nông trại Đắk Lắk",
    farmLocation: "Đắk Lắk",
    rating: 4.9,
    reviewCount: 241,
    sold: 980,
    description: "Bơ Hass hữu cơ từ vườn đồi Đắk Lắk — loại bơ được ưa chuộng nhất thế giới với hàm lượng béo lành mạnh cao. Chín cây, hái tay, không chất kích thích.",
    highlights: [
      "Giống Hass chính gốc — béo ngậy, ít xơ",
      "Chín tự nhiên 100%",
      "Giàu Omega-9 và vitamin E",
      "Không dùng ethylene để thúc chín",
    ],
    nutrition: [
      { label: "Calories", value: "160 kcal / 100g" },
      { label: "Chất béo lành mạnh", value: "14.7g" },
      { label: "Omega-9", value: "9.8g" },
      { label: "Vitamin E", value: "2.1mg" },
      { label: "Kali", value: "485mg" },
      { label: "Folate", value: "81μg" },
    ],
    weight: "2 quả (~400–500g)",
    expiry: "Ăn ngay hoặc bảo quản 3–5 ngày sau khi chín",
    origin: "Đắk Lắk",
  },
  {
    id: 4,
    slug: "rau-xa-lach-butter",
    name: "Rau xà lách butter",
    category: "rau",
    categoryLabel: "Rau xanh",
    price: 28000,
    unit: "300g",
    originalPrice: 38000,
    images: [
      "https://images.unsplash.com/photo-1622205313162-be1d5712a43f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Tươi sạch",
    badgeColor: "bg-teal-500",
    farm: "Nông trại Đà Lạt",
    farmLocation: "Đà Lạt, Lâm Đồng",
    rating: 4.7,
    reviewCount: 189,
    sold: 760,
    description: "Xà lách butter mềm mại, ngọt nhẹ — lý tưởng cho salad và sandwich. Lá to, giòn, không đắng. Trồng trong nhà kính hữu cơ tại Đà Lạt.",
    highlights: [
      "Lá to, mềm mại không đắng",
      "Trồng trong nhà kính kiểm soát",
      "Rửa sạch — dùng được ngay",
      "Thích hợp cho salad và wraps",
    ],
    nutrition: [
      { label: "Calories", value: "13 kcal / 100g" },
      { label: "Vitamin K", value: "102μg (85% DV)" },
      { label: "Vitamin A", value: "166μg" },
      { label: "Folate", value: "73μg" },
      { label: "Chất xơ", value: "1.3g" },
      { label: "Nước", value: "95.6g" },
    ],
    weight: "300g ± 30g",
    expiry: "3–5 ngày trong ngăn mát tủ lạnh",
    origin: "Đà Lạt, Lâm Đồng",
  },
  {
    id: 5,
    slug: "hat-quinoa-huu-co",
    name: "Hạt quinoa hữu cơ",
    category: "hat-ngu-coc",
    categoryLabel: "Hạt & Ngũ cốc",
    price: 125000,
    unit: "500g",
    originalPrice: 165000,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603046891744-76e6300f82ef?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Nhập khẩu",
    badgeColor: "bg-violet-500",
    farm: "Bolivia Organic",
    farmLocation: "Bolivia, Nam Mỹ",
    rating: 4.8,
    reviewCount: 97,
    sold: 430,
    description: "Quinoa hữu cơ nhập khẩu từ Bolivia — vùng trồng quinoa tốt nhất thế giới. Protein hoàn chỉnh với đủ 9 amino acid thiết yếu. Gluten-free, phù hợp cho người ăn chay và chế độ healthy.",
    highlights: [
      "Protein hoàn chỉnh — 9 amino acid thiết yếu",
      "Gluten-free, không biến đổi gen",
      "Giàu sắt và magiê",
      "Chứng nhận hữu cơ Bolivia",
    ],
    nutrition: [
      { label: "Calories", value: "368 kcal / 100g" },
      { label: "Protein", value: "14.1g" },
      { label: "Carbohydrates", value: "64g" },
      { label: "Chất xơ", value: "7g" },
      { label: "Sắt", value: "4.6mg (26% DV)" },
      { label: "Magiê", value: "197mg (47% DV)" },
    ],
    weight: "500g",
    expiry: "24 tháng kể từ ngày sản xuất (bảo quản nơi khô mát)",
    origin: "Bolivia, Nam Mỹ",
  },
  {
    id: 6,
    slug: "dau-tay-da-lat-huu-co",
    name: "Dâu tây Đà Lạt hữu cơ",
    category: "trai-cay",
    categoryLabel: "Trái cây",
    price: 95000,
    unit: "300g",
    originalPrice: 130000,
    images: [
      "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476837579993-f1d3948f17c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1543528176-61b239494933?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Theo mùa",
    badgeColor: "bg-pink-500",
    farm: "Nông trại Đà Lạt",
    farmLocation: "Đà Lạt, Lâm Đồng",
    rating: 5.0,
    reviewCount: 403,
    sold: 1560,
    description: "Dâu tây Đà Lạt chính gốc — ngọt thanh, thơm tự nhiên, không chua gắt. Trồng trong nhà màng hữu cơ, thu hoạch thủ công khi đạt độ chín hoàn hảo. Số lượng có hạn theo mùa vụ.",
    highlights: [
      "Chín cây 100% — ngọt tự nhiên",
      "Trồng trong nhà màng, không thuốc sâu",
      "Giàu vitamin C và antioxidants",
      "Thu hoạch thủ công từng quả",
    ],
    nutrition: [
      { label: "Calories", value: "32 kcal / 100g" },
      { label: "Vitamin C", value: "58.8mg (65% DV)" },
      { label: "Antioxidants", value: "Rất cao" },
      { label: "Chất xơ", value: "2g" },
      { label: "Folate", value: "24μg" },
      { label: "Đường tự nhiên", value: "4.9g" },
    ],
    weight: "300g ± 20g",
    expiry: "2–3 ngày trong ngăn mát tủ lạnh",
    origin: "Đà Lạt, Lâm Đồng",
  },
  {
    id: 7,
    slug: "hung-que-tuoi-huu-co",
    name: "Húng quế tươi hữu cơ",
    category: "thao-moc",
    categoryLabel: "Thảo mộc",
    price: 18000,
    unit: "100g",
    originalPrice: 25000,
    images: [
      "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Thảo mộc",
    badgeColor: "bg-emerald-500",
    farm: "Vườn hữu cơ HCM",
    farmLocation: "Củ Chi, TP.HCM",
    rating: 4.6,
    reviewCount: 156,
    sold: 890,
    description: "Húng quế tươi thơm nức — thu hoạch buổi sáng, giao buổi chiều. Trồng tại vườn hữu cơ Củ Chi, không phân bón hóa học. Lá to, thơm đậm, phù hợp cho phở, bún bò và các món Á.",
    highlights: [
      "Thu hoạch sáng, giao chiều cùng ngày",
      "Thơm đậm — lá to và nguyên vẹn",
      "Không phun thuốc trừ sâu",
      "Phù hợp cho phở, bún, pizza và salad",
    ],
    nutrition: [
      { label: "Calories", value: "22 kcal / 100g" },
      { label: "Vitamin K", value: "414μg (345% DV)" },
      { label: "Vitamin A", value: "264μg" },
      { label: "Magnesium", value: "64mg" },
      { label: "Tinh dầu tự nhiên", value: "Cao" },
      { label: "Antioxidants", value: "Rất cao" },
    ],
    weight: "100g ± 10g",
    expiry: "2–3 ngày trong túi kín, ngăn mát",
    origin: "Củ Chi, TP.HCM",
  },
  {
    id: 8,
    slug: "khoai-lang-tim-huu-co",
    name: "Khoai lang tím hữu cơ",
    category: "cu-qua",
    categoryLabel: "Củ & Quả",
    price: 38000,
    unit: "1kg",
    originalPrice: 52000,
    images: [
      "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80",
    ],
    badge: "Bestseller",
    badgeColor: "bg-purple-500",
    farm: "Nông trại Bến Tre",
    farmLocation: "Bến Tre",
    rating: 4.9,
    reviewCount: 872,
    sold: 3200,
    description: "Khoai lang tím Bến Tre hữu cơ — bùi ngậy, dẻo thơm, màu tím đẹp tự nhiên. Giàu anthocyanin — chất chống oxy hoá mạnh. Phù hợp để luộc, hấp, nướng hay làm bánh.",
    highlights: [
      "Giàu anthocyanin — chống oxy hoá mạnh",
      "Bùi ngậy, ngọt tự nhiên không cần đường",
      "Không dùng hoá chất bảo quản",
      "Đa dụng: luộc, hấp, nướng, sinh tố",
    ],
    nutrition: [
      { label: "Calories", value: "90 kcal / 100g" },
      { label: "Anthocyanin", value: "Rất cao (màu tím)" },
      { label: "Vitamin A", value: "961μg" },
      { label: "Vitamin C", value: "19.6mg" },
      { label: "Chất xơ", value: "3g" },
      { label: "Kali", value: "337mg" },
    ],
    weight: "1kg ± 100g",
    expiry: "14–21 ngày nơi thoáng mát, tránh ánh nắng",
    origin: "Bến Tre",
  },
];

export function getProductById(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.id !== product.id && p.category === product.category)
    .concat(PRODUCTS.filter((p) => p.id !== product.id && p.category !== product.category))
    .slice(0, limit);
}
